
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app
  gen:
    dao:
      link: "pgsql:postgres:Zxsec@123@tcp(192.168.1.23:5432)/firewalld"
      jsonCase: "CamelLower"